export const data = [
  {
    id: 1,
    logo: "https://static-files.birmingham2022.com/photos/flags/AUS.png",
    team: "Australia",
    gold: 0,
    silva: 0,
    bronze: 0,
    total: 0,
  },
  {
    id: 2,
    logo: "https://static-files.birmingham2022.com/photos/flags/ENG.png",
    team: "England",
    gold: 0,
    silva: 0,
    bronze: 0,
    total: 0,
  },
  {
    id: 3,
    logo: "https://static-files.birmingham2022.com/photos/flags/CAN.png",
    team: "Canada",
    gold: 0,
    silva: 0,
    bronze: 0,
    total: 0,
  },
  {
    id: 4,
    logo: "https://static-files.birmingham2022.com/photos/flags/IND.png",
    team: "India",
    gold: 0,
    silva: 0,
    bronze: 0,
    total: 0,
  },
  {
    id: 5,
    logo: "https://static-files.birmingham2022.com/photos/flags/NZL.png",
    team: "New Zealand",
    gold: 0,
    silva: 0,
    bronze: 0,
    total: 0,
  },
  {
    id: 6,
    logo: "https://static-files.birmingham2022.com/photos/flags/SCO.png",
    team: "Scotland",
    gold: 0,
    silva: 0,
    bronze: 0,
    total: 0,
  },
  {
    id: 7,
    logo: "https://static-files.birmingham2022.com/photos/flags/NGR.png",
    team: "Nigeria",
    gold: 0,
    silva: 0,
    bronze: 0,
    total: 0,
  },
  {
    id: 8,
    logo: "https://static-files.birmingham2022.com/photos/flags/WAL.png",
    team: "Wales",
    gold: 0,
    silva: 0,
    bronze: 0,
    total: 0,
  },
  {
    id: 9,
    logo: "https://static-files.birmingham2022.com/photos/flags/RSA.png",
    team: "South Africa",
    gold: 0,
    silva: 0,
    bronze: 0,
    total: 0,
  },
  {
    id: 10,
    logo: "https://static-files.birmingham2022.com/photos/flags/MAS.png",
    team: "Malaysia",
    gold: 0,
    silva: 0,
    bronze: 0,
    total: 0,
  },
];
